# Generated by Django 6.0.4 on 2026-05-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=150)),
                ('Barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Price', models.FloatField()),
                ('Cost', models.FloatField(blank=True, null=True)),
                ('Qty', models.IntegerField(blank=True, null=True)),
                ('Unit', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('CategoryId', models.ForeignKey(db_column='CategoryId', on_delete=django.db.models.deletion.RESTRICT, to='blog_app.category')),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
    ]
